In [11]:
import pandas as pd
import numpy as np

In [12]:
liste_1=[5,10,15,20,25]
pd.DataFrame(data=liste_1, columns=["degerler"],dtype="float")

degerler
0       5.0
1      10.0
2      15.0
3      20.0
4      25.0

In [17]:
# Data frame oluşturma
array_1=np.random.randint(0,50,(4,4))
print(array_1,"\n")
df = pd.DataFrame(data=array_1, index=["a","b","c","d"], columns=["d1","d2","d3","d4"])
print(df,"\n")

[[ 0 36 34  3]
 [12 47 21  0]
 [18 43  1 42]
 [41 48 23 41]] 

   d1  d2  d3  d4
a   0  36  34   3
b  12  47  21   0
c  18  43   1  42
d  41  48  23  41 



In [20]:
x=np.random.randint(10.50,size=6)
y=np.random.randint(10.50,size=6)
z=np.random.randint(10.50,size=6)
w=np.random.randint(10.50,size=6)
print(x,"\n")
sozluk_1={"d1":x,"d2":y,"d3":z,"d4":w}
print(sozluk_1,"\n")
df=pd.DataFrame(data=sozluk_1)
print(df,"\n")

[5 3 0 4 8 9] 

{'d1': array([5, 3, 0, 4, 8, 9]), 'd2': array([0, 7, 6, 8, 1, 1]), 'd3': array([5, 5, 8, 7, 0, 7]), 'd4': array([5, 4, 1, 4, 4, 9])} 

   d1  d2  d3  d4
0   5   0   5   5
1   3   7   5   4
2   0   6   8   1
3   4   8   7   4
4   8   1   0   4
5   9   1   7   9 



In [24]:
# Datayı inceleme
df.head

<bound method NDFrame.head of    d1  d2  d3  d4
0   5   0   5   5
1   3   7   5   4
2   0   6   8   1
3   4   8   7   4
4   8   1   0   4
5   9   1   7   9>

In [26]:
df.head()

d1  d2  d3  d4
0   5   0   5   5
1   3   7   5   4
2   0   6   8   1
3   4   8   7   4
4   8   1   0   4

In [30]:
df.tail

<bound method NDFrame.tail of    d1  d2  d3  d4
0   5   0   5   5
1   3   7   5   4
2   0   6   8   1
3   4   8   7   4
4   8   1   0   4
5   9   1   7   9>

In [32]:
df.tail()

d1  d2  d3  d4
1   3   7   5   4
2   0   6   8   1
3   4   8   7   4
4   8   1   0   4
5   9   1   7   9

In [38]:
df.columns

Index(['d1', 'd2', 'd3', 'd4'], dtype='object')

In [40]:
[i for i in df.columns]

['d1', 'd2', 'd3', 'd4']

In [42]:
df.columns=["n1","n2","n3","n4"]
df.columns

Index(['n1', 'n2', 'n3', 'n4'], dtype='object')

In [49]:
print(type(df.values),'\n')
print(type(df),'\n')
print(df.shape,'\n')
print(df.ndim,'\n')
print(df.size,'\n')


<class 'numpy.ndarray'> 

<class 'pandas.core.frame.DataFrame'> 

(6, 4) 

2 

24 

