In [1]:
import numpy as np

In [2]:
array=np.arange(0,11)
array[4]

4

In [3]:
degisken=np.array([[5,10,15],[20,230],[35,40,45]])
degisken

/tmp/ipykernel_22492/3684699781.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  degisken=np.array([[5,10,15],[20,230],[35,40,45]])


array([list([5, 10, 15]), list([20, 230]), list([35, 40, 45])],
      dtype=object)

In [4]:
print(degisken[2][1])

40


In [5]:
array=np.arange(10,20)
print(array)
print(array[1:10:2])
print(array[3::2])
print(array[:7:3])

[10 11 12 13 14 15 16 17 18 19]
[11 13 15 17 19]
[13 15 17 19]
[10 13 16]


In [6]:
array=np.arange(30).reshape(5,6)
print(array)
print('\n')
print(array[2])
print('\n')
print(array[:,3])
print('\n')
print(array[:3,:-2])
print('\n')
print(array[0::2,0::2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


[12 13 14 15 16 17]


[ 3  9 15 21 27]


[[ 0  1  2  3]
 [ 6  7  8  9]
 [12 13 14 15]]


[[ 0  2  4]
 [12 14 16]
 [24 26 28]]


In [7]:
degisken=np.array([0,1,2,3,7,5,6,4,8,3])
degisken[4]=4
degisken[7]=7
degisken[9]=9
print(degisken)
degisken=np.array([0,1,2,3,7,5,6,4,8,3])
degisken[:4]=10
print(degisken)
degisken=np.array([0,1,2,3,7,5,6,4,8,3])
degisken[4:]=10
print(degisken)

[0 1 2 3 4 5 6 7 8 9]
[10 10 10 10  7  5  6  4  8  3]
[ 0  1  2  3 10 10 10 10 10 10]


In [8]:
ornek=np.arange(0,100,10)
print(ornek,'\n')

ornek=np.delete(ornek,0).reshape(3,3)
ornek[1,1]=100
print(ornek,'\n')

ornek[1,0]=40.5
print(ornek,'\n')

ornek[:,2]=100
print(ornek,'\n')

ornek[0::2,:]=100
print(ornek,'\n')

ornek[0]=10,20,30
print(ornek,'\n')

[ 0 10 20 30 40 50 60 70 80 90] 

[[ 10  20  30]
 [ 40 100  60]
 [ 70  80  90]] 

[[ 10  20  30]
 [ 40 100  60]
 [ 70  80  90]] 

[[ 10  20 100]
 [ 40 100 100]
 [ 70  80 100]] 

[[100 100 100]
 [ 40 100 100]
 [100 100 100]] 

[[ 10  20  30]
 [ 40 100 100]
 [100 100 100]] 



In [9]:
fancy=np.arange(0,50,5)
print(fancy,"\n")

print(fancy[1],fancy[3],fancy[5],'\n')

indexes=[1,3,5]
print(fancy[indexes],'\n')

indexes=np.array([1,3,5])
print(fancy[indexes],'\n')


[ 0  5 10 15 20 25 30 35 40 45] 

5 15 25 

[ 5 15 25] 

[ 5 15 25] 



In [10]:
array=np.zeros((10,10),dtype='int')
print(array,"\n\n", array.shape,"\n")

row=array.shape[0]

for i in range(row):
    array[i]=i

print(array,"\n")

liste_1=[1,3,5,7]
print(array[liste_1],"\n")

liste_2=[8,5,2,0]
print(array[liste_2],"\n")

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 

 (10, 10) 

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]] 

[[1 1 1 1 1 1 1 1 1 1]
 [3 3 3 3 3 3 3 3 3 3]
 [5 5 5 5 5 5 5 5 5 5]
 [7 7 7 7 7 7 7 7 7 7]] 

[[8 8 8 8 8 8 8 8 8 8]
 [5 5 5 5 5 5 5 5 5 5]
 [2 2 2 2 2 2 2 2 2 2]
 [0 0 0 0 0 0 0 0 0 0]] 



In [11]:
degisken=np.arange(1,17).reshape(4,4)
print(degisken,"\n")

print(degisken[[0,3],[1,2]],"\n")

row=[0,2,3,1]
column=[3,0,2,1]

print(degisken[row,column])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[ 2 15] 

[ 4  9 15  6]


In [12]:
degisken=np.arange(1,17).reshape(4,4)
print(degisken,"\n")

print(degisken[1,[0,3]],"\n")

print(degisken[[0,3],1],"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[5 8] 

[ 2 14] 



In [13]:
degisken=np.arange(1,17).reshape(4,4)

print(degisken[:,1:3],"\n")

print(degisken[1:3,[1,2]],"\n")


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

[[ 6  7]
 [10 11]] 

