In [91]:
# array numpy kütüphanesi içinde bulunan veri tipi
import numpy as np

In [92]:
list(np.array([2,4,6,8]))

[2, 4, 6, 8]

In [93]:
variable=[5.8,9,4,2]
print(type(variable[0]))
print(type(variable[1]))

<class 'float'>
<class 'int'>


In [94]:
new_variable_1=np.array([5.8,9,4,2])
print(type(new_variable_1[0]))
print(type(new_variable_1[1]))
print(new_variable_1)

<class 'numpy.float64'>
<class 'numpy.float64'>
[5.8 9.  4.  2. ]


In [95]:
new_variable_2=np.array([5.8,9,4,2],dtype="int")
print(type(new_variable_2[0]))
print(type(new_variable_2[1]))
print(new_variable_2)

<class 'numpy.int64'>
<class 'numpy.int64'>
[5 9 4 2]


In [96]:
#np.zeros() istediğimiz boyutta sıfırladan oluşan bir dizi
print(np.zeros((5)))
print("\n")
print(np.zeros((3,5), dtype="int"))

[0. 0. 0. 0. 0.]


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [97]:
#np.ones() istediğimiz boyutta birlerden oluşan bir dizi
print(np.ones((5)))
print("\n")
print(np.ones((3,4,5), dtype="int"))

[1. 1. 1. 1. 1.]


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [98]:
#np.full() istediğimiz boyutta istediğimiz sayılardan bir dizi
print(np.full(5,6))
print("\n")
print(np.full((3,4,5), 6, dtype="float"))

[6 6 6 6 6]


[[[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]

 [[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]

 [[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]]


In [99]:
#np.arange() belirlediğimiz başlangıç ve bitiş noktasına göre istedğimiz türe göre np arrayi
print(np.arange(5))
print("\n")
print(np.arange(3, 10, dtype="float"))

[0 1 2 3 4]


[3. 4. 5. 6. 7. 8. 9.]


In [100]:
 #np.eye() birim matrisi
print(np.eye(3))
print(np.eye(3,2))
print(np.eye(3,3,dtype="bool"))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[ True False False]
 [False  True False]
 [False False  True]]


In [101]:
#np.linspace() iki değer arasında belli sayıda değer oluşturma
print(np.linspace(10,30,10,dtype="int"))

[10 12 14 16 18 21 23 25 27 30]


In [102]:
#np.random() rastagele array
print(np.random.rand(5))
print(np.random.rand(2,3))

[0.3363195  0.0876161  0.2015242  0.23892873 0.84355812]
[[0.96394854 0.56899267 0.73489372]
 [0.3788845  0.90017197 0.27040987]]


In [103]:
print(np.random.normal(5))
print(np.random.normal(20,5,(4,3)))

5.026927767065552
[[18.88964522 18.94656986 18.51170254]
 [20.75012859 17.48975631 22.25098603]
 [16.14915488 19.91285289 29.96383736]
 [17.55996797 21.49697514 23.42090553]]


In [104]:
print(np.random.randint(0,10,(4,4)))

[[2 3 9 1]
 [8 0 7 3]
 [0 7 9 3]
 [1 1 1 7]]


In [105]:
matrix=np.random.randint(10,50,(5,4))
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)


[[31 18 28 46]
 [46 35 12 47]
 [35 36 31 49]
 [22 41 14 48]
 [48 19 40 42]]
2
(5, 4)
20
int64
