In [2]:
import numpy as np

In [3]:
ornek=np.arange(1,16)
ornek.reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
array=ornek.reshape((1,15))
print(array.ndim)
print(ornek.ndim)

2
1


In [5]:
#np.argmax() ve np.max()
array_1=np.random.randint(0,50,10)
print(array_1)
print(array_1.max())
print(array_1.argmax())


[11 35 49  9  2 32 43 44 28 47]
49
2


In [6]:
array_2=np.random.randint(0,50,(4,3))
print(array_2)
print(array_2.max())
print(array_2.argmax())

[[ 6 21 44]
 [ 7 38 49]
 [45  3  3]
 [47 14 30]]
49
5


In [7]:
#np.argmin() ve np.min()
array_1=np.random.randint(20,70,10)
print(array_1)
print(array_1.min())
print(array_1.argmin())

[35 32 21 46 31 21 39 45 59 65]
21
2


In [8]:
array_2=np.random.randint(20,70,(4,3))
print(array_2)
print(array_2.min())
print(array_2.argmin())

[[58 38 59]
 [37 67 23]
 [44 64 27]
 [30 52 28]]
23
5


In [9]:
#np.concatenate()
array_1=np.array([1,2,3,4])
array_2=np.array([5,6,7,8])
np.concatenate([array_1,array_2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
array_3=np.arange(1,7).reshape((2,3))
array_3

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array_4=np.array([[7,8,9],[10,11,12]])
array_4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [12]:
print(np.concatenate([array_3,array_4],axis=0))
print('\n')
print(np.concatenate([array_3,array_4],axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [13]:
#np.split()
array_1=np.array([1,3,5,50,50,2,4,6])
print(np.split(array_1,[3,5]))
x,y,z=np.split(array_1,[3,5])
print(x,y,z)
print(np.split(array_1,4))

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]
[1 3 5] [50 50] [2 4 6]
[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]


In [14]:
array_1=np.arange(20).reshape(5,4)
print(array_1,'\n')
x,y,z=np.split(array_1,[1,3])
print(x,y,z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[0 1 2 3]] [[ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]
 [16 17 18 19]]


In [15]:
np.split(array_1,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [16]:
#np.hsplit()
print(np.hsplit(array_1,4))

[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]]), array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])]


In [17]:
print(np.hsplit(array_1,[1,3]))

[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])]


In [18]:
#np.vsplit()
np.vsplit(array_1,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [19]:
np.vsplit(array_1,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [20]:
#np.sort()
degisken1=np.array([2,5,6,1,9,8])
print(degisken1)
degisken2=np.sort(degisken1)
print(degisken2)

[2 5 6 1 9 8]
[1 2 5 6 8 9]


In [21]:
degisken1=np.random.normal(30,5,(4,4))
degisken2=np.sort(degisken1,axis=1)
degisken3=np.sort(degisken1,axis=0)
print(degisken2)
print(degisken3)

[[20.12677289 25.69702927 27.77386654 33.14732991]
 [15.81879317 18.33417712 29.35124031 39.27372064]
 [26.30295645 29.59311238 35.1486133  37.13088825]
 [24.21501967 25.69934094 33.37006466 36.33073062]]
[[26.30295645 18.33417712 15.81879317 20.12677289]
 [33.14732991 25.69702927 27.77386654 24.21501967]
 [36.33073062 25.69934094 33.37006466 29.35124031]
 [39.27372064 29.59311238 37.13088825 35.1486133 ]]
