In [56]:
import numpy as np

In [57]:
array=np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
array>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
array[array>5]

array([ 6,  7,  8,  9, 10])

In [60]:
kaz=array>=5
array[kaz]

array([ 5,  6,  7,  8,  9, 10])

In [61]:
#and
k1=(array != 8) & (array>=6)
array[k1]

array([ 6,  7,  9, 10])

In [62]:
#or
k1=(array != 8) | (array>=6)
array[k1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
array-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [64]:
array*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [65]:
array/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [66]:
((array * 10) + 20) / 5

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [67]:
array*array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [68]:
# çıkarma
print(np.subtract(array,2),'\n')
# çarpma
print(np.multiply(array,10),'\n')
# toplama
print(np.add(array,20),'\n')
# bölme
print(np.divide(array,10),'\n')
# üs alma
print(array**3,'\n')
# üs alma
print(np.power(array,3),'\n')
# karekök alma
print(np.sqrt(100),'\n')
# kalan
print(np.mod(array,7),'\n')
# sinüs
print(np.sin(array),'\n')
# kosinüs
print(np.cos(array),'\n')
# logaritma
print(np.log10(array),'\n')

[-1  0  1  2  3  4  5  6  7  8] 

[ 10  20  30  40  50  60  70  80  90 100] 

[21 22 23 24 25 26 27 28 29 30] 

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 

[   1    8   27   64  125  216  343  512  729 1000] 

[   1    8   27   64  125  216  343  512  729 1000] 

10.0 

[1 2 3 4 5 6 0 1 2 3] 

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111] 

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153] 

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ] 



In [75]:
# toplam 
print(np.sum(array),'\n')
# ortalama
print(np.mean(array),'\n')
#median
print(np.median(array),'\n')
# en küçük değer
print(np.min(array),'\n')
# en büyük değer
print(np.max(array),'\n')

55 

5.5 

5.5 

1 

10 



In [78]:
# standart sapma
print(np.std(array),'\n')
# varyans
print(np.var(array),'\n')

2.8722813232690143 

8.25 



In [190]:
# np.linalg()
coef=np.array([[2,1],[-3,6]])
out=np.array([5,0])
np.linalg.solve(coef,out)


array([2., 1.])