In [26]:
import numpy as np

In [27]:
array=np.arange(1,11)
array2=np.arange(11,21).reshape(2,5)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
degisken1=np.array([2,5,6,1,9,8,12,45,1233,2,45,124,21,56])
dag=(degisken1>3) & (degisken1 <= 21)
degisken1[dag]

array([ 5,  6,  9,  8, 12, 21])

In [50]:
array=np.full((3,3),5)
array

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [55]:
array=np.linspace(10,10.1,10)
array

array([10.        , 10.01111111, 10.02222222, 10.03333333, 10.04444444,
       10.05555556, 10.06666667, 10.07777778, 10.08888889, 10.1       ])

In [65]:
array=np.arange(1,51).reshape(10,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [71]:
array[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25],
       [31, 33, 35],
       [41, 43, 45]])